export const countryCodeIban = 
[
{code:'ad', country: "Andorra"},
{code:'ae', country: "EAU"},
{code:'af', country: "Afganistán"},
{code:'ag', country: "Antigua y Barbuda"},
{code:'ai', country: "Anguila"},
{code:'al', country: "Albania"},
{code:'am', country: "Armenia"},
{code:'ao', country: "Angola"},
{code:'aq', country: "Antártida"},
{code:'ar', country: "Argentina"},
{code:'as', country: "Samoa Americana"},
{code:'at', country: "Austria"},
{code:'au', country: "Australia"},
{code:'aw', country: "Aruba"},
{code:'ax', country: "Islas Åland"},
{code:'az', country: "Azerbaiyán"},
{code:'ba', country: "Bosnia Herz."},
{code:'bb', country: "Barbados"},
{code:'bd', country: "Bangladesh"},
{code:'be', country: "Bélgica"},
{code:'bf', country: "Burkina Faso"},
{code:'bg', country: "Bulgaria"},
{code:'bh', country: "Bahrain"},
{code:'bi', country: "Burundi"},
{code:'bj', country: "Benin"},
{code:'bl', country: "San Bartolomé"},
{code:'bm', country: "Bermudas"},
{code:'bn', country: "Brunéi"},
{code:'bo', country: "Bolivia"},
{code:'br', country: "Brasil"},
{code:'bs', country: "Bahamas"},
{code:'bt', country: "Bhutan"},
{code:'bw', country: "Botswana"},
{code:'by', country: "Bielorrusia"},
{code:'bz', country: "Belize"},
{code:'ca', country: "Canadá"},
{code:'cc', country: "Islas Cocos"},
{code:'cd', country: "RD Congo"},
{code:'cf', country: "R. Centroafricana"},
{code:'cg', country: "Congo"},
{code:'ch', country: "Suiza"},
{code:'ci', country: "Costa de Marfil"},
{code:'ck', country: "Islas Cook"},
{code:'cl', country: "Chile"},
{code:'cm', country: "Camerún"},
{code:'cn', country: "China"},
{code:'co', country: "Colombia"},
{code:'cr', country: "Costa Rica"},
{code:'cu', country: "Cuba"},
{code:'cv', country: "Cabo Verde"},
{code:'cw', country: "Curaçao"},
{code:'cx', country: "Islas Christmas"},
{code:'cy', country: "Chipre"},
{code:'cz', country: "Rep. Checa"},
{code:'de', country: "Alemania"},
{code:'dj', country: "Djibouti"},
{code:'dk', country: "Dinamarca"},
{code:'dm', country: "Dominica"},
{code:'do', country: "Rep. Dominicana"},
{code:'dz', country: "Argelia"},
{code:'ec', country: "Ecuador"},
{code:'ee', country: "Estonia"},
{code:'eg', country: "Egiptp"},
{code:'eh', country: "Sáhara"},
{code:'er', country: "Eritrea"},
{code:'es', country: "España"},
{code:'et', country: "Etiopía"},
{code:'eu', country: "UE"},
{code:'fi', country: "Finlandia"},
{code:'fj', country: "Fiji"},
{code:'fk', country: "Malvinas"},
{code:'fm', country: "Micronesia"},
{code:'fo', country: "Islas Feroe"},
{code:'fr', country: "Francia"},
{code:'ga', country: "Gabón"},
{code:'gb', country: "Reino Unido"},
{code:'gb-eng', country: "Inglaterra"},
{code:'gb-nir', country: "Irlanda Nor."},
{code:'gb-sct', country: "Escocia"},
{code:'gb-wls', country: "Gales"},
{code:'gd', country: "Granada"},
{code:'ge', country: "Georgia"},
{code:'gf', country: "Guayana francesa"},
{code:'gg', country: "Guernsey"},
{code:'gh', country: "Ghana"},
{code:'gi', country: "Gibraltar"},
{code:'gl', country: "Groenlandia"},
{code:'gm', country: "Gambia"},
{code:'gn', country: "Guinea"},
{code:'gp', country: "Guadalupe"},
{code:'gq', country: "Guinea ecuatorial"},
{code:'gr', country: "Grecia"},
{code:'gs', country: "Georgia del Sur"},
{code:'gt', country: "Guatemala"},
{code:'gu', country: "Guam"},
{code:'gw', country: "Guinea-Bissau"},
{code:'gy', country: "Guayana"},
{code:'hk', country: "Hong Kong"},
{code:'hn', country: "Honduras"},
{code:'hr', country: "Croacia"},
{code:'ht', country: "Haití"},
{code:'hu', country: "Hungría"},
{code:'id', country: "Indonesia"},
{code:'ie', country: "Irlanda"},
{code:'il', country: "Israel"},
{code:'im', country: "Isla de Man"},
{code:'in', country: "India"},
{code:'iq', country: "Irak"},
{code:'ir', country: "Irán"},
{code:'is', country: "Islandia"},
{code:'it', country: "Italia"},
{code:'je', country: "Jersey"},
{code:'jm', country: "Jamaica"},
{code:'jo', country: "Jordania"},
{code:'jp', country: "Japón"},
{code:'ke', country: "Kenya"},
{code:'kg', country: "Kyrgyzstan"},
{code:'kh', country: "Camboya"},
{code:'ki', country: "Kiribati"},
{code:'km', country: "Comoros"},
{code:'kp', country: "Corea del Norte"},
{code:'kr', country: "Corea del Sur"},
{code:'kw', country: "Kuwait"},
{code:'ky', country: "Islas Caimán"},
{code:'kz', country: "Kazajistán"},
{code:'la', country: "Laos"},
{code:'lb', country: "Líbano"},
{code:'lc', country: "Santa Lucía"},
{code:'li', country: "Liechtenstein"},
{code:'lk', country: "Sri Lanka"},
{code:'lr', country: "Liberia"},
{code:'ls', country: "Lesotho"},
{code:'lt', country: "Lituania"},
{code:'lu', country: "Luxemburgo"},
{code:'lv', country: "Letonia"},
{code:'ly', country: "Libia"},
{code:'ma', country: "Marruecos"},
{code:'mc', country: "Monaco"},
{code:'md', country: "Moldavia"},
{code:'me', country: "Montenegro"},
{code:'mg', country: "Madagascar"},
{code:'mh', country: "Islas Marshall"},
{code:'mk', country: "Macedonia"},
{code:'ml', country: "Mali"},
{code:'mm', country: "Myanmar"},
{code:'mn', country: "Mongolia"},
{code:'mo', country: "Macao"},
{code:'mq', country: "Martinica"},
{code:'mr', country: "Mauritania"},
{code:'ms', country: "Montserrat"},
{code:'mt', country: "Malta"},
{code:'mu', country: "Mauritius"},
{code:'mv', country: "Maldivas"},
{code:'mw', country: "Malawi"},
{code:'mx', country: "México"},
{code:'my', country: "Malasia"},
{code:'mz', country: "Mozambique"},
{code:'na', country: "Namibia"},
{code:'nc', country: "Nueva Caledonia"},
{code:'ne', country: "Níger"},
{code:'ng', country: "Nigeria"},
{code:'ni', country: "Nicaragua"},
{code:'nl', country: "Países Bajos"},
{code:'no', country: "Noruega"},
{code:'np', country: "Nepal"},
{code:'nr', country: "Nauru"},
{code:'nu', country: "Niue"},
{code:'nz', country: "Nueva Zelanda"},
{code:'om', country: "Omán"},
{code:'pa', country: "Panamá"},
{code:'pe', country: "Perú"},
{code:'pg', country: "Papúa N.Guinea"},
{code:'ph', country: "Filipinas"},
{code:'pk', country: "Pakistán"},
{code:'pl', country: "Polonia"},
{code:'pr', country: "Puerto Rico"},
{code:'ps', country: "Palestina"},
{code:'pt', country: "Portugal"},
{code:'pw', country: "Palau"},
{code:'py', country: "Paraguay"},
{code:'qa', country: "Qatar"},
{code:'re', country: "Reunión"},
{code:'ro', country: "Rumania"},
{code:'rs', country: "Serbia"},
{code:'ru', country: "Rusia"},
{code:'rw', country: "Rwanda"},
{code:'sa', country: "Arabia Saudí"},
{code:'sb', country: "Islas Salomón"},
{code:'sc', country: "Seychelles"},
{code:'sd', country: "Sudán"},
{code:'se', country: "Sweden"},
{code:'sg', country: "Singapur"},
{code:'si', country: "Eslovenia"},
{code:'sk', country: "Eslovaquia"},
{code:'sl', country: "Sierra Leona"},
{code:'sm', country: "San Marino"},
{code:'sn', country: "Senegal"},
{code:'so', country: "Somalia"},
{code:'sr', country: "Surinam"},
{code:'ss', country: "Sudán del Sur"},
{code:'sv', country: "El Salvador"},
{code:'sy', country: "Siria"},
{code:'sz', country: "Suazilandia"},
{code:'td', country: "Chad"},
{code:'tg', country: "Togo"},
{code:'th', country: "Tailandia"},
{code:'tj', country: "Tajikistán"},
{code:'tk', country: "Tokelau"},
{code:'tl', country: "Timor Oriental"},
{code:'tm', country: "Turkmenistán"},
{code:'tn', country: "Tunez"},
{code:'to', country: "Tonga"},
{code:'tr', country: "Turquía"},
{code:'tt', country: "Trinidad y Tobago"},
{code:'tv', country: "Tuvalu"},
{code:'tw', country: "Taiwán"},
{code:'tz', country: "Tanzania"},
{code:'ua', country: "Ucrania"},
{code:'ug', country: "Uganda"},
{code:'un', country: "Naciones Unidas"},
{code:'us', country: "EE.UU."},
{code:'uy', country: "Uruguay"},
{code:'uz', country: "Uzbekistán"},
{code:'va', country: "Vaticano"},
{code:'ve', country: "Venezuela"},
{code:'vn', country: "Vietnam"},
{code:'vu', country: "Vanuatu"},
{code:'ws', country: "Samoa"},
{code:'xk', country: "Kosovo"},
{code:'ye', country: "Yemen"},
{code:'yt', country: "Mayotte"},
{code:'za', country: "Sudáfrica"},
{code:'zm', country: "Zambia"},
{code:'zw', country: "Zimbabwe"},
]